name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            # cloning the project
            repo=/tmp/api-article
            if cd ${repo}; then 
              git pull; 
            else 
              git clone git@github.com:rezpaditya/api-article.git ${repo}; 
              cd ${repo}
            fi

            # building the docker image
            docker build -t api-article .
            
            # running docker image
            docker stop api-article  || echo "Continueing..."
            docker run --rm -d -p 8000:80 --name api-article api-article 

            exit_code=$?
            if ${exit_code} -ne 0; then
              echo 'Something went wrong!'
            else  
              echo 'Deployment to DigitalOcean is finished successfully!'
            fi

            exit ${exit_code}